### ISSUE TITLE
Create Seurat Object where features are common gene names

### ISSUE THREAD

**Issue by rossana24** [ElyasMo/ST.mtx#1]
I'm using your tool to have a look at my spatial transcriptomics data, as the h5 files are missing.
The Seurat object that I have obtained presents the gene_ids as features (e.g., ENSG00000187634, ENSG00000188976), whereas my requirement is for common gene names as features, such as SAMD11 and NOC2L.

Is there a way method to achieve this?

Thank you in advance for your help

**Comment by ElyasMo** [comment]
Dear @rossana24,
First you need to convert your Ensemble IDs to Gene symbols. This might be a good start using Biomart R package: (https://www.biostars.org/p/9540029/). 
Next, you need to add the gene Symbols to the first column of your features.tsv as by default, Read10X considers the features in the first column (gene.column = 1). Then you should be good to go with the ST.mtx to read your ST profiles.
